### ISSUE TITLE
export to SPSS losing information

### ISSUE THREAD

**Issue by pierrelafortune** [leeper/rio#121] opened 2016-09-15 20:13 UTC
After reading in an sav file and writing to disk, I noticed the size of the file dramatically increased. Also, labels and other information was lost.

To isolate the issue and be sure that my process was not affecting the output, I read in the file and immediately wrote it out to check the difference:

```
library(rio)
full <- import("~/testinput.sav")
export(full, file="~/testoutput.sav")
```

Original file size; rio output file size

![file_window](https://cloud.githubusercontent.com/assets/8163470/18565772/0fa66874-7b5f-11e6-877e-f6c2d4cd11fc.png)

Original with labels

![labels](https://cloud.githubusercontent.com/assets/8163470/18565776/11f42c7e-7b5f-11e6-864b-e785b0ff816b.png)

rio output: labels, values, Column, Width all affected

![nolabels](https://cloud.githubusercontent.com/assets/8163470/18565782/197a3d12-7b5f-11e6-8448-bbcc4cfe5a06.png)

**Comment by leeper** [comment] 2017-05-14 13:23
@pierrelafortune Can you try this again with the most recent version of rio? (I don't have access to SPSS so I'm unable to test it).

**Comment by leeper** [comment] 2017-06-16 15:08
I'm closing this. If the issue is still occurring, I will reopen.

**Closed by leeper** 2017-06-16 15:08 UTC
Labels: bug, format-attributes
