### ISSUE TITLE
CRAN: package rio is now scheduled for archival on 2021-11-15

### ISSUE THREAD

**Issue by OVVO-Financial** [leeper/rio#289] opened 2021-11-01 11:38 UTC
Just received the following email from Prof. Brian Ripley:

We have asked for an update fixing the check problems shown at
  <https://urldefense.proofpoint.com/v2/url?u=https-3A__cran.r-2Dproject.org_web_checks_check-5Fresults-5Frio.html&d=DwIDaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=ZsV2iIQnScGn47R7XoBbGxOwUnmCtKM1TGDnqtB2EKs&m=1vb6HcbAhF2-hHb13C1CYjcmnFEx2fzMtb_djoWLcsVa-L5jMKdbNtS9QpCajcVL&s=HdSCM9_zc5pomC_PKRwf41yEgr-muyJTbKpBFaq0_b8&e= >
with no update from the maintainer thus far.

Thus, package rio is now scheduled for archival on 2021-11-15, and
archiving this will necessitate also archiving its strong reverse
dependencies.

Please negotiate the necessary actions.

The CRAN Team

**Comment by greenpiolin** [comment] 2021-11-01 12:25
Dear Mantainer:

After removing the file test-all.R at test directory the package is built correctly and pass the check.

I don't know the role of this file, but could it be a workaround to delete it?

My best, Manuel

**Comment by chainsawriot** [comment] 2021-11-01 20:39
@MMunozMarquez That could be a fix. But it means the package will not be tested on CRAN anymore.

By reading the log, there are two problems:

1. [the warnings triggered by "type.convert" for the XML import](https://github.com/leeper/rio/blob/7b178212795c687f17030b70e52cc2abe7939fa3/R/import_methods.R#L380).
2. The random segfault of [is_file_text()](https://github.com/leeper/rio/blob/main/R/is_file_text.R).

I think 1. is pretty easy to fix. I will submit a PR later. (@leeper would it be helpful? Or you have fixed it already?)
I need to dig deeper to understand 2.

**Comment by chainsawriot** [comment] 2021-11-01 22:14
Apropos 2.

From the Github Actions' [log](https://github.com/leeper/rio/pull/290), the segfault appears to be related to packages using xml2. It could be `readODS::read_ods` or `pzfx::write_pzfx`. As I am the maintainer of `readODS`, I am investigating what went wrong. But I don't see problems in readODS Github Actions' check log.

This could be the reason: r-lib/xml2#339.

**Comment by chainsawriot** [comment] 2021-11-02 14:21
The curious thing about the `rmatio` segfault is that it was triggered by `test_that::skip_if_not_installed()`; exactly at the step of `requireNamespace`. And it is a base function... I don't know if something sinister is going on.

**Comment by chainsawriot** [comment] 2021-11-02 22:55
The strange thing about those segfault errors is: I can't reproduce them when I isolate the tests.

https://github.com/chainsawriot/dummypkg/actions/runs/1414423857

**Comment by leeper** [comment] 2021-11-06 14:07
Thanks for this debugging, @chainsawriot! I'll get these things merged. As a hotfix, I may turn off the tests for `is_file_text()` and then try to fix. The segfault on skipping tests is weird...

**Comment by chainsawriot** [comment] 2021-11-08 19:40
@leeper I think the old 0.5.27 is no longer having the segfault on CRAN suddenly.

(And of course, the M1 check done by BDR on 02-11 does not get updated)

https://cran.r-project.org/web/checks/check_results_rio.html

**Comment by bokov** [comment] 2021-11-30 21:22
But how do we handle the getting-archived issue? Should we resubmit?

This is in my opinion the best, cleanest data import package in R, let's not let it die.

**Comment by chainsawriot** [comment] 2021-12-01 08:59
@bokov I think it's saved. @leeper has submitted a new version.

https://cran.r-project.org/web/checks/check_results_rio.html

**Closed** 2021-12-20 13:01 UTC
