### ISSUE TITLE
rio error with development version of haven:

### ISSUE THREAD

**Issue by hadley** [leeper/rio#193] opened 2018-10-23 18:55 UTC
``` r
packageVersion("haven")
#> [1] '1.1.2.9000'
packageVersion("rio")
#> [1] '0.5.10'

e <- rio::import("http://www.stata-press.com/data/r13/auto.dta")
g <- rio::gather_attrs(e)
g$foreign
#> <Labelled double>
#> Error: `x` and `labels` must be same type
```

I'm not sure exactly what is causing this, but it's probably related to the changes to the [labelled class](https://github.com/tidyverse/haven/blob/master/NEWS.md#breaking-changes).

Could you please take a look? I'm planning on submitting haven 2.0 to CRAN on [November 7](https://github.com/tidyverse/haven/issues/399)

**Comment by leeper** [comment] 2018-11-25 20:19
Duplicate of #188

**Closed by leeper** 2018-11-25 20:19 UTC
Labels: bug
